# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'myproject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myproject
 pod 'React', :path => './react/node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
'RCTImage',
'RCTNetwork',  
  'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
end
